// <auto-generated />
using System;
using Lib.Core.EF.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20230303195129_offlinedata123252")]
    partial class offlinedata123252
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Lib.Core.EF.DbObjects.DataEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UOM1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UOM1Value")
                        .HasColumnType("REAL");

                    b.Property<string>("UOM2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UOM2Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DataEntries");
                });

            modelBuilder.Entity("Lib.Core.EF.DbObjects.SynchronizationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeSynced")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Synchronizations");
                });
#pragma warning restore 612, 618
        }
    }
}
